### PR TITLE
7.15 SDK

### PR DESCRIPTION
**Pull request by kkdai**

### CODE REVIEW

**Comment by Barney30818** [comment]
So I couldn't deploy to Heroku because it was stuck at build stage, the error message was the same with this pr's build pipeline.

**Review by kkdai — COMMENTED** [review]
LGTM

**Comment by kkdai** [comment]
@Barney30818 Hi, Sorry for that. It has been fixed.

**Comment by Barney30818** [comment]
Thank you so much, it works now!

**Pull request merged**
